name: netmanager
description: "A Material mobile network monitoring app built with ease-of-use and speed in mind."
publish_to: 'none'

version: 0.0.1+3

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  dynamic_color: ^1.8.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  sentry_flutter: ^9.8.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png